export enum ErrorType {
  UNKNOWN = 0,

  APNG_ACCESS_ERORR = 10, // 実行ファイルのアクセスに失敗
  APNG_OTHER_ERORR,
  APNG_ERORR,

  WEBP_ERROR = 20,

  CWEBP_ACCESS_ERROR = 30, // 実行ファイルのアクセスに失敗
  CWEBP_OTHER_ERROR,
  CWEBP_ERROR,

  WEBPMUX_ACCESS_ERROR = 40, // 実行ファイルのアクセスに失敗
  WEBPMUX_OTHER_ERROR,
  WEBPMUX_ERROR,

  HTML_ERROR = 50,

  MAKE_TEMPORARY_ERROR = 60,
  TEMPORARY_CLEAN_ERROR,
  FILE_MOVE_ERROR,

  PNG_COMPRESS_ERROR = 70,
  PNG_COMPRESS_ACCESS_ERROR, // 実行ファイルのアクセスに失敗
  PNG_COMPRESS_OTHER_ERROR,
  PNG_COMPRESS_QUALITY_ERROR // pngquant99エラー
}
